name = "cloak_wrapper"
version = "1.0.0"
description = "Gleam wrapper for Cloak (Elixir)"
licences = ["MIT"]
repository = { type = "github", user = "bchase", repo = "cloak_wrapper" }
# links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
cloak = ">= 1.1.4 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
